### ISSUE TITLE
Typo in managementgroups / API Version 2023-04-01

### ISSUE THREAD

**Issue by jkroepke** [hashicorp/go-azure-sdk#1025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Used

ManagementGroups

### API Versions Used

2023-04-01

### Description

All subscription related Method function have a typo.

https://github.com/hashicorp/go-azure-sdk/blob/main/resource-manager/managementgroups/2023-04-01/managementgroups/method_ubscriptionscreate.go

A `S` is missing at front. `ubscriptions` vs `subscriptions`

**Comment by tombuildsstuff** [comment]
hey @jkroepke 

Thanks for reporting this, I've opened https://github.com/hashicorp/pandora/pull/4255 which should fix this - once that's merged the SDK will be regenerated and this'll become `Subscriptions` rather than `Ubscriptions`.

Thanks!
