### ISSUE TITLE
Support for Synapse / 2021-06-01

### ISSUE THREAD

**Issue by ms-henglu** [hashicorp/go-azure-sdk#107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Name

Synapse

### API Versions Required

2021-06-01

**Comment by tombuildsstuff** [comment]
@ms-henglu could you clarify if this is for Resource Manager or Data Plane?

**Comment by tombuildsstuff** [comment]
Closing this since we've not heard back
