### ISSUE TITLE
Support for Cognitive / 2022-03-01

### ISSUE THREAD

**Issue by ms-henglu** [hashicorp/go-azure-sdk#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Name

Cognitive

### API Versions Required

2022-03-01

**Comment by tombuildsstuff** [comment]
`2022-10-01` is now available which should supersede this, but let us know if `2022-03-01` is also needed and we can look to support that: https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/cognitive/2022-10-01
