### ISSUE TITLE
Support for devopsinfrastructure / 2024-04-04-preview

### ISSUE THREAD

**Issue by brittandeyoung** [hashicorp/go-azure-sdk#1081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

I would like to be able to write terraform resources for these associated services. It looks like this needs to support the needed service before work can start on the provider side. 

### Service Name

devopsinfrastructure

### API Versions Required

2024-04-04-preview

### References

This is to enable building out associated resources for the terraform-provider-azurerm https://github.com/hashicorp/terraform-provider-azurerm/issues/26412

**Comment by manicminer** [comment]
Added in https://github.com/hashicorp/go-azure-sdk/pull/1082
