### ISSUE TITLE
Support for Automation / 2019-06-01

### ISSUE THREAD

**Issue by jhisc** [hashicorp/go-azure-sdk#116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Name

Automation

### API Versions Required

2019-06-01

### References

[REST API Spec](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/automation/resource-manager/Microsoft.Automation/stable/2019-06-01)

**Comment by jhisc** [comment]
To provide some additional input incase you require it.
I'm looking to add Python support to the Azure Runbook resource. Microsoft have updated the API docs to include this and also the resource-manager within the Go SDK. However the have not updated the `services/` directory.

As a result this appears to be the only (and possibly the more appropriate) way to achieve this.

**Comment by tombuildsstuff** [comment]
@jhisc thanks for reaching out / apologies for the delay - looking into this now 👍

**Comment by tombuildsstuff** [comment]
Fixed via #131
