### ISSUE TITLE
Support for KeyVault data-plane / 7.3

### ISSUE THREAD

**Issue by wuxu92** [hashicorp/go-azure-sdk#118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Name

KeyVault

### API Versions Required

keyvault data-plane 7.3

spec definition: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.3

### References

Is there a plan/schedule to add `data-plane` API support in this SDK?

**Comment by tombuildsstuff** [comment]
@wuxu92 Data Plane could be supported in the future - but that's not something we support today - in the interim this'll need to be done via a Track1 SDK/release.

**Comment by lkurzyniec** [comment]
Hi @tombuildsstuff, is there a chance to deliver this one rather sooner than later? It seems to be a blocker for #14471.

**Comment by tombuildsstuff** [comment]
Dependent on https://github.com/Azure/azure-rest-api-specs/pull/21137

**Comment by tombuildsstuff** [comment]
Version 7.4 of the Key Vault Data Plane API is available in Kermit (which provides Track1 versions of SDKs): https://github.com/tombuildsstuff/kermit/tree/main/sdk/keyvault/7.4/keyvault
