### ISSUE TITLE
Support for dataprotection / 2022-05-01

### ISSUE THREAD

**Issue by rndmh3ro** [hashicorp/go-azure-sdk#123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Name

dataprotection

### API Versions Required

2022-05-01

### References

This new API Version is required to set `ZoneRedundant` in the `azurerm_data_protection_backup_vault` module, mentioned in this issue:
https://github.com/hashicorp/terraform-provider-azurerm/issues/17906

**Comment by tombuildsstuff** [comment]
Fixed via #132
