### ISSUE TITLE
Support for loadtestservice / 2022-06-01-preview

### ISSUE THREAD

**Issue by heoelri** [hashicorp/go-azure-sdk#142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Name

loadtestservice

### API Versions Required

2022-06-01-preview

### References

This superseeds issue #133. 

The currently used API version `2021-12-01-preview` will be deprecated soon. 

See https://github.com/hashicorp/terraform-provider-azurerm/issues/18185 for more.

**Comment by tombuildsstuff** [comment]
hey @heoelri 

Thanks for requesting this, unfortunately [there isn't Swagger for the Resource Manager API version `2022-06-01-preview` yet](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/loadtestservice/resource-manager/Microsoft.LoadTestService/preview) - based on [this PR](https://github.com/Azure/azure-rest-api-specs/pull/20258/files#diff-262117912d3566b2001f1600a35dc583aad24a0bf202ff2fd6ef2ba9f3d1eb79R1490) I'm wondering if API Version `2022-06-01-preview` is a Data Plane only API and if API Version `2022-04-15-preview` is the latest Resource Manager API version?

As such we can look to add support for the Resource Manager API version `2022-04-15-preview` for now (which appears to be the latest version of this API), but unfortunately we can't support `2022-06-01-preview` until there's Swagger available for it. Have you got any more context for this API version to determine if this is a Resource Manager or Data Plane API version perchance?

Thanks!

**Comment by heoelri** [comment]
Maybe @ninallam can shed some light here.

**Comment by ninallam** [comment]
Hi @tombuildsstuff The latest Data Plane API version is 2022-06-01-preview and Resource Manager API version is 2022-04-15-preview.

**Comment by tombuildsstuff** [comment]
@ninallam thanks for the confirmation - is there a timeline for when a stable API Version will become available?

**Comment by tombuildsstuff** [comment]
API Version `2022-04-15-preview` can be found here: https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/loadtestservice/2022-04-15-preview ([Documentation](https://pkg.go.dev/github.com/hashicorp/go-azure-sdk@v0.20220915.1151935/resource-manager/loadtestservice/2022-04-15-preview/loadtests)) - closing this out since `2022-06-01` is a Data Plane only API.
