### ISSUE TITLE
Support for Azure Stack HCI / 2022-09-01

### ISSUE THREAD

**Issue by liuwuliuyun** [hashicorp/go-azure-sdk#147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Name

Azure Stack HCI

### API Versions Required

2022-09-01

### References

https://github.com/Azure/azure-rest-api-specs/tree/main/specification/azurestackhci/resource-manager/Microsoft.AzureStackHCI/stable/2022-09-01

**Comment by tombuildsstuff** [comment]
This is now available: https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/azurestackhci/2022-09-01
