### ISSUE TITLE
Support for ContainerService / 2022-04+

### ISSUE THREAD

**Issue by aristosvo** [hashicorp/go-azure-sdk#157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Name

ContainerService

### API Versions Required

2022-04-02-preview, 2022-05-02-preview, 2022-06-02-preview, 2022-07-02-preview or 2022-08-02-preview

Anything that supports `enableVnetIntegration`

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/18500

**Comment by djsly** [comment]
I was also looking at how I could add the support for Windows2022, after 1 hours of trying to undestand, I came to the same conclusion that missing releases needed to be packaged / imported differently. 

I'm not sure how complex it would be to add a new resourcegroup

**Comment by aristosvo** [comment]
PR submitted for Pandora: https://github.com/hashicorp/pandora/pull/1669

**Comment by tombuildsstuff** [comment]
This'll be available in the next Release, happening shortly - thanks for the PR @aristosvo :)

**Comment by djsly** [comment]
@tombuildsstuff how often does the azurerm provider picks up new release of this project ?

**Comment by tombuildsstuff** [comment]
@djsly at the moment it's done manually/as needed - right now we're doing it roughly weekly but we can do it more frequently/as needed, I believe the changes for this have already been merged in since @aristosvo has a PR open: https://github.com/hashicorp/terraform-provider-azurerm/pull/18705.

**Comment by djsly** [comment]
Awesome!   I see that this might go in the next release. I’ll wait for it to be merge and I’ll start adding some new missing features in azurerm! On Oct 14, 2022, at 8:43 AM, Tom Harvey ***@***.***> wrote:﻿
@djsly at the moment it's done manually/as needed - right now we're doing it roughly weekly but we can do it more frequently/as needed, I believe the changes for this have already been merged in since @aristosvo has a PR open: hashicorp/terraform-provider-azurerm#18705.
