### ISSUE TITLE
Support for DesktopVirtualization / 2022-04-01-preview

### ISSUE THREAD

**Issue by alexwilcox9** [hashicorp/go-azure-sdk#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Name

desktopvirtualization

### API Versions Required

2022-04-01-preview

### References

https://github.com/Azure/azure-rest-api-specs/pull/21641

**Comment by tombuildsstuff** [comment]
@alexwilcox9 apologies for the delayed reply, there's a Stable API version (2022-09-09) - would that work for you, or do you need this Preview version too? https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/desktopvirtualization

**Comment by alexwilcox9** [comment]
Hi @tombuildsstuff 

Thew new stable API version does the job for me, thanks for letting me know. I'll close the issue down now
