### ISSUE TITLE
Issue with Authorization / Role Management Policies / API Version 2020-10-01

### ISSUE THREAD

**Issue by josh-barker** [hashicorp/go-azure-sdk#288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Used

Authorization / Role Management Policies

### API Versions Used

2020-10-01

### Description

Hi, I'm working on a new AzureRM Terraform resource - `azurerm_role_management_policy`, which will manage PIM settings on a scope and role definition combination.

The issue I have with the SDK is that I cannot get the configuration for a specific scope and role definition, as there is no `$filter` parameter for the API call.

Microsoft has published an example on how to get and update a management policy - https://learn.microsoft.com/en-us/rest/api/authorization/privileged-role-policy-rest-sample.

The example returns configuration for a specific scope and role definition.
Example API call: `GET https://management.azure.com/{scope}/providers/Microsoft.Authorization/roleManagementPolicies?api-version=2020-10-01&$filter=roleDefinitionId%20eq%20'{scope}/providers/Microsoft.Authorization/roleDefinitions/{roleDefinitionId}'`.

Note: The response does not include `role_definition_id`, so we cannot filter the whole list to choose the correct element.

FYI: @manicminer 

### References

- https://github.com/Azure/azure-sdk-for-go/issues/17728

**Comment by tombuildsstuff** [comment]
SDK PR: https://github.com/hashicorp/go-azure-sdk/pull/588

**Comment by josh-barker** [comment]
Thanks @tombuildsstuff !
