### ISSUE TITLE
Issue with DNS / API Version 2018-05-01

### ISSUE THREAD

**Issue by liuwuliuyun** [hashicorp/go-azure-sdk#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Used

DNS

### API Versions Used

2018-05-01

### Description

In zones.method_list.go https://github.com/hashicorp/go-azure-sdk/blob/2fad35bb42dfb97bbc27e72ee0e125ee6690f533/resource-manager/dns/2018-05-01/zones/method_list.go#L81 should be `value` instead of `values`

### References

https://github.com/Azure/azure-rest-api-specs/blob/add28efcd3a5fd422285d992fb1ec5ee5a7a40a6/specification/dns/resource-manager/Microsoft.Network/stable/2018-05-01/dns.json#L1567-L1582

**Comment by tombuildsstuff** [comment]
Thanks for reporting this @liuwuliuyun 

Taking a look through here I'd wager this is the same issue as #356 - which looks to be coming from here: https://github.com/hashicorp/pandora/blob/42ac9d9d024377a051bd20cac5b00dd977f31794/tools/generator-go-sdk/generator/templater_methods.go#L545

**Comment by tombuildsstuff** [comment]
Fixed via #388
