### ISSUE TITLE
Issue with DataProtection / API Version 2022-04-01

### ISSUE THREAD

**Issue by mbfrahry** [hashicorp/go-azure-sdk#431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Used

Data Protection

### API Versions Used

2022-04-01

### Description

There is an issue with [DeleteAfter](https://github.com/hashicorp/go-azure-sdk/blob/main/resource-manager/dataprotection/2022-04-01/backuppolicies/model_sourcelifecycle.go#L12).

It isn't a pointer
<img width="816" alt="image" src="https://user-images.githubusercontent.com/6515518/234136906-e3b711a9-7243-4686-baab-831cff8acb90.png">

but we're setting it as one during [UnmarshalJSON](https://github.com/hashicorp/go-azure-sdk/blob/main/resource-manager/dataprotection/2022-04-01/backuppolicies/model_sourcelifecycle.go#L39)

<img width="199" alt="image" src="https://user-images.githubusercontent.com/6515518/234137018-a3b57811-5c65-4f87-8340-192b519ec8d1.png">

If you print that attribute, you can get an address back (`0x14000c989c0`) which would mean we have to do some funkiness by casting twice like so

```
deleteOptionPtr := *retentionRule.Lifecycles[0].DeleteAfter.(*backuppolicies.DeleteOption)
if deleteOption, ok := deleteOptionPtr.(backuppolicies.AbsoluteDeleteOption); ok {
	return deleteOption.Duration, nil
}
```

**Comment by tombuildsstuff** [comment]
This is intentional/by design, since we need to be able to set a null value for this discriminated field, it's not ideal but unfortunately the lack of fidelity in the Swagger means this is our best option at this point in time to be able to send a null value for these fields
