### ISSUE TITLE
Support for ContainerService / 2023-03-02-preview

### ISSUE THREAD

**Issue by Vegoo89** [hashicorp/go-azure-sdk#466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Name

containerservice

### API Versions Required

2023-03-02-preview

### References

Support for customCATrustCertificates in ManagedClusterSecurityProfile

Docs reference: https://learn.microsoft.com/en-us/azure/templates/microsoft.containerservice/2023-03-02-preview/managedclusters?pivots=deployment-language-bicep#managedclustersecurityprofile

**Comment by tombuildsstuff** [comment]
hey @Vegoo89 

Thanks for opening this issue - I've opened https://github.com/hashicorp/go-azure-sdk/issues/466 which'll (once merged) will import into `hashicorp/pandora` and then generated this API version into this repository for use.

Thanks!
