### ISSUE TITLE
Header Issue with marketplaceordering / API Version 2021-01-01

### ISSUE THREAD

**Issue by mbfrahry** [hashicorp/go-azure-sdk#497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Used

MarketPlaceOrdering

### API Versions Used

2021-01-01

### Description

[MarketPlaceAgreementsCancel](https://github.com/hashicorp/go-azure-sdk/blob/main/resource-manager/marketplaceordering/2021-01-01/agreements/method_marketplaceagreementscancel.go#L38) is failing because there isn't a header being added for `content-length`

Here is the request
```
:authority: management.azure.com
:method: POST
:path: some-path
:scheme: https
authorization: some-auth-token
x-ms-correlation-request-id: 71dc3a9e-3a0c-1e88-aaeb-240a69f05c74
content-type: application/json
user-agent: HashiCorp/go-azure-sdk (Go-http-Client/1.1 agreements/2021-01-01) HashiCorp Terraform/ (+https://www.terraform.io) Terraform Plugin SDK/2.10.1 terraform-provider-azurerm/acc pid-222c6c49-1b0a-5959-a213-6608f9eb8820
accept-encoding: gzip
```

And the error being returned
```
<BODY><h2>Length Required</h2>
<hr><p>HTTP Error 411. The request must be chunked or have a content length.</p>
</BODY></HTML>
```

Adding `content-length: 0` to the request headers fixes this issue.

**Comment by tombuildsstuff** [comment]
Duplicate of https://github.com/hashicorp/go-azure-sdk/pull/448 - which'll be fixed by https://github.com/hashicorp/go-retryablehttp/pull/194

**Comment by tombuildsstuff** [comment]
I believe this should be fixed now, @mbfrahry mind taking another look at this one?

**Comment by mbfrahry** [comment]
It is! Thanks @tombuildsstuff!
