### ISSUE TITLE
Unmarshal Issue with StorageSync / API Version 2020-03-01

### ISSUE THREAD

**Issue by mbfrahry** [hashicorp/go-azure-sdk#498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Used

StorageShare

### API Versions Used

2020-03-01

### Description

Seeing an issue when un-marshling the response from [Get](https://github.com/hashicorp/go-azure-sdk/blob/main/resource-manager/storagesync/2020-03-01/syncgroupresource/method_syncgroupsget.go#L46) a StorageSyncGroup. 

```
json: cannot unmarshal object into Go struct field error.details of type []struct { Code *string "json:\"code\""; Target *string "json:\"target\""
```

This can be replicated in about a minute by pulling down this [branch](https://github.com/hashicorp/terraform-provider-azurerm/pull/21928) and running the `TestAccStorageSyncGroup_basic` test.

**Comment by mbfrahry** [comment]
I believe the `StorageSync` package is un-marshaling funkily as every test is failing with that same unmarshal error

<img width="542" alt="image" src="https://github.com/hashicorp/go-azure-sdk/assets/6515518/05ef6468-8dec-4375-88fa-664f0f1cdd50">

**Comment by mbfrahry** [comment]
Fixed by https://github.com/hashicorp/go-azure-sdk/pull/501#pullrequestreview-1466159702

**Comment by tombuildsstuff** [comment]
@mbfrahry mind checking if 21928 above is fixed when it's rebased on `main`?

**Comment by mbfrahry** [comment]
It works! Ty ty!
