### ISSUE TITLE
Support for iotcentral / 2022-07-31dataplane and/or 2022-10-31-previewdataplane

### ISSUE THREAD

**Issue by KenSpur** [hashicorp/go-azure-sdk#527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Name

Iotcentral

### API Versions Required

https://learn.microsoft.com/en-us/rest/api/iotcentral/

* 2022-07-31dataplane
* 2022-10-31-previewdataplane

**Comment by KenSpur** [comment]
Thanks!

**Comment by KenSpur** [comment]
@tombuildsstuff how can i now use the data plane SDK?

**Comment by tombuildsstuff** [comment]
@KenSpur apologies, looks like there was a data issue - I've opened https://github.com/tombuildsstuff/kermit/pull/236 which fixes that, once that's merged another `Data` PR will be generated containing the SDK, and once that's merged it'll be released/available for use.

**Comment by KenSpur** [comment]
@tombuildsstuff thanks!
