### ISSUE TITLE
Network  / API Version 2022-09-01 - Application Security Group Association for Private Endpoint

### ISSUE THREAD

**Issue by mbfrahry** [hashicorp/go-azure-sdk#533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Used

Network

### API Versions Used

2022-09-01

### Description

I'm looking to migrate `azurerm_private_endpoint_application_security_group_association`. In this resource, we are doing a Get call from the application security group client and appending that to the [private endpoint model](https://github.com/hashicorp/go-azure-sdk/blob/main/resource-manager/network/2022-09-01/privateendpoints/model_privateendpointproperties.go#L7). 

Though the application security group models are the same from [privateendpoints](https://github.com/hashicorp/go-azure-sdk/blob/main/resource-manager/network/2022-09-01/privateendpoints/model_applicationsecuritygroup.go) and [applicationsecuritygroups](https://github.com/hashicorp/go-azure-sdk/blob/main/resource-manager/network/2022-09-01/applicationsecuritygroups/model_applicationsecuritygroup.go), go doesn't like it as they are two separate packages. 

I believe we need a way to copy the model from `applicationsecuritygroups` into the one from `privateendpoints`

**Comment by tombuildsstuff** [comment]
@mbfrahry this only actually needs the `ID` to map across, so whilst these are two distinct object types in two different packages, it should be sufficient to specify:

```go
if ASGList != nil {
				*ASGList = append(*ASGList, privateendpoints.ApplicationSecurityGroup{
					Id: other.Id,
				})
				input.ApplicationSecurityGroups = ASGList
			} else {
				input.ApplicationSecurityGroups = &[]privateendpoints.ApplicationSecurityGroup{
					{
						Id: other.Id,
					},
				}
			}
```

Can you take a look and see if that works for you here?

**Comment by tombuildsstuff** [comment]
@mbfrahry given https://github.com/hashicorp/terraform-provider-azurerm/pull/22396 I'm going to close this issue for the moment?
