### ISSUE TITLE
Support for ContainerRegistry / 2023-01-01-preview

### ISSUE THREAD

**Issue by nclaeys** [hashicorp/go-azure-sdk#544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Name

ContainerRegistry

### API Versions Required

2023-01-01-preview

### References

Start on implementing support for caching of acr in the azurerm-terraform-provider: https://github.com/hashicorp/terraform-provider-azurerm/issues/21258

**Comment by tombuildsstuff** [comment]
hey @nclaeys 

Thanks for opening this issue - apologies for the delayed response here.

I've just opened https://github.com/hashicorp/pandora/pull/2852 which (once merged) will send a PR adding support for this API Version to `hashicorp/go-azure-sdk`.

Thanks!

**Comment by nclaeys** [comment]
@tombuildsstuff Any update on when this will be merged? Just making sure we can make progress on the ticket...

**Comment by tombuildsstuff** [comment]
@nclaeys apologies for the delay - FWIW it looks like this is available in the latest Stable API (which got released this morning): https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/containerregistry/2023-07-01/cacherules - so I believe we should be able to use that Stable API version rather than a Preview API version here?

**Comment by nclaeys** [comment]
@tombuildsstuff even better, yes indeed let's use the stable API version instead.

**Comment by tombuildsstuff** [comment]
I'm going to close this / https://github.com/hashicorp/pandora/pull/2852 out since there's a Stable API version available - but if there's a need for the Preview let us know and we can look to add support for that one 👍

**Comment by bkarakashev** [comment]
@tombuildsstuff  the ACR Cache rules are not our of preview and in production. Are you able to add support for it in terraform? 
Many thanks
