### ISSUE TITLE
Issue with [Automation] / API Version [2021-06-22]

### ISSUE THREAD

**Issue by wuxu92** [hashicorp/go-azure-sdk#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Used

Automation

### API Versions Used

2021-06-22

### Description

the create method of `hybridrunbookworkergroup` check status only 200, but for create api the service can always return status code as 201, and this sdk will raise an error.

related code line: https://github.com/hashicorp/go-azure-sdk/blob/323c45e04cf4580f5eae24fd60b9f1122eee052a/resource-manager/automation/2021-06-22/hybridrunbookworkergroup/method_create_autorest.go#L63

**Comment by tombuildsstuff** [comment]
@wuxu92 unfortunately this is ultimately a Swagger issue since the Resource only defines a 200 as the response, so this'll need to be fixed there in the short-term (by adding a 201 to the response).

Longer term this is something we'll look to address on our side too (depending on whether it's a LRO/not) - but ultimately this'd need to be fixed in the Swagger in the interim, so would you mind [opening an issue on the Swagger repository](https://github.com/Azure/azure-rest-api-specs) for this?

Thanks!

**Comment by tombuildsstuff** [comment]
In the interim it should be possible to workaround this by checking the HTTP Status Code being returned here, for example:

```go
ctx := context.TODO()
id := hybridrunbookworkergroup.NewHybridRunbookWorkerGroupID("12345678-1234-9876-4563-123456789012", "example-resource-group", "automationAccountValue", "hybridRunbookWorkerGroupValue")

payload := hybridrunbookworkergroup.HybridRunbookWorkerGroupCreateOrUpdateParameters{
	// ...
}


read, err := client.Create(ctx, id, payload)
if err != nil {
	// workaround [LINK TO API ISSUE]
	if !response.WasStatusCode(read.HttpResponse, http.Created) {
		// handle the error
	}
}
if model := read.Model; model != nil {
	// do something with the model/response object
}
```

This'll involve the `WasStatusCode` method being exposed within the `response` package, which I'll be sending a PR for shortly.

**Comment by tombuildsstuff** [comment]
`WasStatusCode` will be exposed in https://github.com/hashicorp/go-azure-helpers/pull/124
