### ISSUE TITLE
Support for [resource-manager] / [2022-12-02]

### ISSUE THREAD

**Issue by HappyTobi** [hashicorp/go-azure-sdk#634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

I need a newer version of the Microsoft.Resources provider to extend the existing Azure Terraform data resource: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/extended_locations#extended_locations

The requirement is to provide more information about the "subscription" like Zonal support, etc.

There also exist an issue that can be closed with an api / provider update (https://github.com/hashicorp/terraform-provider-azurerm/issues/3025)

### Service Name

Resources

### API Versions Required

2022-12-02

### References

https://learn.microsoft.com/en-us/rest/api/resources/
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Resources/stable/2022-12-01/subscriptions.json

**Comment by HappyTobi** [comment]
@tombuildsstuff is it possible to add the resources to the sdk?

Thank you
Regards

**Comment by tombuildsstuff** [comment]
@HappyTobi fwiw this has been in the SDK for a while now and can be found here: https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/resources/2022-12-01 👍

**Comment by HappyTobi** [comment]
@tombuildsstuff 

Cool, when I looked into it was not there.
Thanks a lot
