### ISSUE TITLE
Support for Linux and Windows AAD Login adding Guid to 'well known'

### ISSUE THREAD

**Issue by DevopsMercenary** [hashicorp/go-azure-sdk#656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Name

Active Directory Auth

### API Versions Required

Not really sure nor important I think

### References

I would like to see if two more 'Well Known' App Ids for microsoft azure could be added.

from these two pages

https://learn.microsoft.com/en-us/azure/active-directory/devices/howto-vm-sign-in-azure-ad-linux
https://learn.microsoft.com/en-us/azure/active-directory/devices/howto-vm-sign-in-azure-ad-windows

"Microsoft Azure Linux Virtual Machine Sign-In" with guid  ce6ff14a-7fdc-4685-bbe0-f6afdfcfa8e0

"Azure Windows VM Sign-In" with guid 372140e0-b3b7-4226-8ef9-d57986796201

Thank you

**Comment by DevopsMercenary** [comment]
Also...

"Microsoft Intune Enrollment"
d4ebce55-015a-49b5-a083-c84d1797ae8c

**Comment by manicminer** [comment]
@DevopsMercenary Thanks for requesting these, I've opened #662 to add them
