### ISSUE TITLE
Issue with [operationalinsights] / API Version [2021-06-01] - LRO operation does not expect 202 status code

### ISSUE THREAD

**Issue by ziyeqf** [hashicorp/go-azure-sdk#735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Used

loganalytics

### API Versions Used

2021-06-01

### Description

The method is only expecting HTTP 200, code [link](https://github.com/hashicorp/go-azure-sdk/blob/2f657f88f54209572bfb6236828a01ebbaafa0bc/resource-manager/operationalinsights/2021-06-01/clusters/method_update.go#L28), while it's a LRO, and it will return HTTP 202. I assume it's a Swagger issue, so I opened one for that: https://github.com/Azure/azure-rest-api-specs/issues/26678
But just a thought if we can add 202 to `ExpectedStatusCodes` for LROs when generating the sdk?

**Comment by tombuildsstuff** [comment]
@ziyeqf 

> But just a thought if we can add 202 to ExpectedStatusCodes for LROs when generating the sdk?

In this case the data needs to be updated, as you've done in [this PR](https://github.com/Azure/azure-rest-api-specs/pull/26679) however we can [look to add a Data Workaround](https://github.com/hashicorp/pandora/blob/main/tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_authorization_25080.go) for this in the interim to workaround this issue - until the upstream issue is resolved.

I've added the upstream PR to our list of open issues fwiw, so we can track that on there 👍

**Comment by tombuildsstuff** [comment]
Fixed via https://github.com/hashicorp/pandora/pull/3478
