### ISSUE TITLE
Support for Microsoft.Insights scheduledQueryRules / 2023-03-15-preview

### ISSUE THREAD

**Issue by ASHR4** [hashicorp/go-azure-sdk#845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Name

Montitor

### API Versions Required

2023-03-15-preview

This is the latest version that allows Microsoft.Insights scheduledQueryRules to be configured with a managed identity

### References

[terraform-provider-azurerm issue #23437](https://github.com/hashicorp/terraform-provider-azurerm/issues/23437)

**Comment by tombuildsstuff** [comment]
hey @ASHR4 

Thanks for opening this issue.

I've opened https://github.com/hashicorp/pandora/pull/3702 which'll import this API Version into Pandora - once that's merged (and the imported API Definitions have been reviewed) - a PR will be generated adding the SDK for this API version, which'll fix this issue.

Thanks!
