### ISSUE TITLE
Support for Advisor / 2023-01-01

### ISSUE THREAD

**Issue by jkroepke** [hashicorp/go-azure-sdk#992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

# Goal

I would like to setup Advisor Suppressions via Terraform. While I was integrate the resource provider, I saw that a client does not exists.

### Service Name

Advisor

### API Versions Required

2023-01-01

### References

* https://learn.microsoft.com/en-us/rest/api/advisor/suppressions/create?view=rest-advisor-2023-01-01&tabs=HTTP

**Comment by tombuildsstuff** [comment]
hey @jkroepke 

Taking a look through, it appears that [this is available here](https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/advisor/2023-01-01/suppressions) - would you be able to take a look and see if that works for you?

Thanks!

**Comment by jkroepke** [comment]
Looks good. I didn't not see it initially.
